dist: xenial
language: python
sudo: false
python:
- 3.5
- 3.6
- 3.7
install:
- pip install -U pip setuptools
- pip install pytest-runner
script:
- python setup.py test

notifications:
  email:
    on_success: change
    on_failure: always
